
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable Python Scripts
python_script:
logger:
    default: debug

# Enable HACS
hacs:
    token: !secret github_token

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# LIFX Lights
lifx:
  light:
    - server: 192.168.1.3
      port: 56700
      broadcast: 192.168.107.20
    - server: 192.168.1.3
      port: 56700
      broadcast: 192.168.107.21

# # Tapo Smart Plugs
# tplink:
#   discovery: false
#   switch:
#   - host: 192.168.107.70
#   - host: 192.168.107.71

# Spotify
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password

# Lounge TV
webostv:
  host: 192.168.1.55
  name: Lounge TV
  customize:
    sources:
      - livetv
      - netflix
      - amazonprime

# Allow Themes
frontend:
  themes: !include_dir_merge_named themes
